language: python
python:
  - "3.6"
  - "nightly"
# command to install dependencies
install:
  - pip install travis-sphinx
  - pip install -r requirements-dev.txt
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest
  - travis-sphinx -v build -n --source docs

after_success:
  - travis-sphinx -v deploy
